### ISSUE TITLE
Sounds from the "Typing Sound"? 

### ISSUE THREAD

**Issue by NiKola-UE** [ahmedthebest31/navsounds#12]
Hello, @ahmedthebest31, 

Would it be possible to add sounds from 
[this addon ](https://github.com/abdallah-hader/typing_settings) 
as a new option, in addition to the already existing scheme? "Typing Sound" is already incompatible with the latest version of the NVDA, although it can work, and the author @abdallah-hader does not respond to comments. Of course, I don't think you need to update that addon, but that the sounds from that addon can be incorporated into this one because I like to use them at the same time. 

Also, it seems to me that the previous version of "Navigation Sound" had a little more options, because the sound that I would describe as a Windows Notify was not "statistic" by default in the "Choose a sound" option, that is, another could have been used for it.

**Comment by ahmedthebest31** [comment]
Thanks for your feedback, Nikola-UE.


# about updates: 
major NVDA updates (like 2024.1) might require addon updates. However, for minor updates (like 2024.2 and 2024.3), usually only the manifest file needs adjusting. I try to avoid unnecessary updates that users wouldn't benefit from, like those just for manifest changes.


# Sounds:

You're right about the navigation and typing sounds. To reduce addon size, I removed some options. However, you can easily add custom sounds by:

1. Opening the addon file in "navSounds/globalPlugins/effects/".
2. Copying or creating the desired sound folders from the other addon.
3. Restarting NVDA.


Since everyone has different preferences, I include the essential navigation and typing sounds in the main addon. But, this method allows you to easily add anything extra you like.


Please let me know if you have any questions about it.

**Comment by NiKola-UE** [comment]
Thanks for the quick response. Yes, the latest version of NVDA addons that were updated at the end of last year already recognizes them as incompatible and even warns users about possible dangers and some kind of risk, which can sometimes be tiring, but that's already the problem of the program itself. 




I use both "Navigation Sound" and "Typing Sounds" together without any problems, with "Navigation Sound" available in the Addon Store and updated. I also like it when there are more options and the size doesn't bother me, but it's a matter of user experience. It is interesting that some addons in the Store are available in multiple versions and they are all compatible at the same time, so maybe that can be used in the sense that there can be minor differences between them like the one I mentioned in relation to multiple options.

**Comment by NiKola-UE** [comment]
Let me clarify a little what I wanted to say. Namely, in the first option for selecting sounds, there is a "VoiceOver" scheme, which is also an addon. It occurred to me to add an option in which it would be possible to use sounds from "Typing Sounds", but so that several sounds can be used simultaneously, so like these two addons. How feasible is this?

**Comment by NiKola-UE** [comment]
@ahmedthebest31 ahmedthebest31 


When I think about it a bit more, it will be quite enough that when opening a program or loading a site or page, some other sound other than the Windows Notify can be heard, as was already possible in the previous version. Some new options may wait for one of the next updates.

**Comment by ahmedthebest31** [comment]
The sound you hear when a webpage or desktop application finishes loading has been a consistent feature of this add-on since version 1.0.

In addition to modifying the sound and keyboard typing schemes, you can also customize or create your own sounds. This allows you to personalize your NavSound experience.

If you can specify which version of the add-on introduced the sound you mentioned, or if you have suggestions for new sound schemes or keyboard sounds, please submit a pull request.

**Comment by NiKola-UE** [comment]
@ahmedthebest31 

I'm not a programmer and I don't know much about these things, but I remember well that in one of the versions of this addon from last year (I'll check which one it is and let you know if you agree) it was possible that after finishing and loading, instead of the mentioned sound, another sound could be heard , and that's the only thing I would like to change somehow. So, it's not a problem with the already existing schemes that suit me perfectly, but I would just like to change that one sound, which in the "Select sound" option, as it seems to me, is currently not possible.

**Comment by NiKola-UE** [comment]
Dear @ahmedthebest31, 












I can confirm that the sound heard after loading or opening a program or page is not the same in all versions because it is not there at all in the first published version (v1.0.0), but in this latest 1.5.1 it is noticeably different from the one from, for example, the version 1.3.0 or similar, which you as the developer you understand better than me. I don't mind the changes, but I wish it could be changed in the settings like all the other sounds and schemes because I don't like it when I hear the same sound constantly so often no matter what scheme I've chosen and I can't change it. So, no really needs for pul requests, and all old versions are also still available here, ie. in the "Released" page. 






I'll close this issue because I've said everything I wanted to, and others have already been opened where similar suggestions are made. 















All the best and thank you.
